version: '3.3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php_fpm
    ports:
      - "5000:8000"
    volumes:
      - ../pay-sales-staff:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1

